name: TestIgnore

on:
  push:
    tags:
      - '*'
    branches:
      - master

jobs:
  build:
    name: Test job
    runs-on: macOS-10.14
    steps:
    - uses: actions/checkout@v1
    - name: Test
      run: |
        echo "event ${{ github.event_name }} ref: ${{ github.ref }}"
    - name: ReleaseTest
      if: github.event_name	== 'push' && startsWith(github.ref, 'refs/tags/v')
      run: |
        echo "Would have released"
